// <auto-generated />
using System;
using DienThoaiWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DienThoaiWeb.Migrations
{
    [DbContext(typeof(DienThoaiDbContext))]
    [Migration("20260724115410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DienThoaiWeb.Models.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KhachHangMaKH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaKH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDH");

                    b.HasIndex("KhachHangMaKH");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DienThoaiWeb.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DienThoaiWeb.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPU")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraSau")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraTruoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DungLuongPin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiaTriKhuyenMai")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeDieuHanh")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("KhuyenMai")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManHinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("RAM")
                        .HasColumnType("TEXT");

                    b.Property<string>("ROM")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoDanhGia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoSao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheNho")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSP = "Sam0",
                            CameraSau = "13 MP",
                            CameraTruoc = "5 MP",
                            Gia = "3.490.000",
                            HeDieuHanh = "Android 8.1 (Oreo)",
                            HinhAnh = "img/products/samsung-galaxy-j4-plus-pink-400x400.jpg",
                            ManHinh = "IPS LCD, 6.0', HD+",
                            SoDanhGia = 26,
                            SoSao = 3,
                            TenSP = "SamSung Galaxy J4+",
                            ThuongHieu = "Samsung"
                        },
                        new
                        {
                            MaSP = "Xia0",
                            CameraSau = "12 MP và 5 MP (2 camera)",
                            CameraTruoc = "24 MP",
                            Gia = "6.690.000",
                            HeDieuHanh = "Android 8.1 (Oreo)",
                            HinhAnh = "img/products/xiaomi-mi-8-lite-black-1-600x600.jpg",
                            ManHinh = "IPS LCD, 6.26', Full HD+",
                            SoDanhGia = 0,
                            SoSao = 0,
                            TenSP = "Xiaomi Mi 8 Lite",
                            ThuongHieu = "Xiaomi"
                        },
                        new
                        {
                            MaSP = "Opp0",
                            CameraSau = "16 MP và 2 MP (2 camera)",
                            CameraTruoc = "25 MP",
                            Gia = "7.690.000",
                            HeDieuHanh = "ColorOS 5.2 (Android 8.1)",
                            HinhAnh = "img/products/oppo-f9-red-600x600.jpg",
                            ManHinh = "LTPS LCD, 6.3', Full HD+",
                            SoDanhGia = 188,
                            SoSao = 5,
                            TenSP = "Oppo F9",
                            ThuongHieu = "Oppo"
                        });
                });

            modelBuilder.Entity("DienThoaiWeb.Models.DonHang", b =>
                {
                    b.HasOne("DienThoaiWeb.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKH");

                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
